- test/alias/BUILD
- test/alias/README.md
- test/alias/a.h
- test/alias/b.h
- test/alias/no_dependencies.cpp
- test/alias/use_a_and_b.cpp
- test/execute_tests.py
Resolves: https://github.com/martis42/depend_on_what_you_use/issues/20
> Add acceptance tests for aliases

- README.md
- docs/design_principle.md
Various refactoring and resolves https://github.com/martis42/depend_on_what_you_use/issues/19
> Work on documentation

- foo
This file should never have reached the main branch.
> Remove notes file for previous feature

- .github/workflows/ci.yaml
- test/apply_fixes/execute_tests.py
- test/apply_fixes/execute_tests_impl.py
1. Generalize acceptance test script for automatic fixes
2. Add test for `--dry-run` option
> Add test for dry run option for automatic fixes working as expected

- .github/workflows/ci.yaml
- README.md
- src/apply_fixes/main.py
- test/apply_fixes/execute_tests.py
- test/apply_fixes/execute_tests_impl.py
Mitigate https://github.com/martis42/depend_on_what_you_use/issues/39
> Improve apply fixes usability

- README.md
- Use tar.gz over .zip
- Make clear an archive checksum is optional
- Clearer wording
> Doc: Improve doc for using a specific commit

- README.md
- docs/project_design_rationales.md
- src/analyze_includes/get_dependencies.py
- src/analyze_includes/main.py
- src/analyze_includes/parse_source.py
- src/aspect/dwyu.bzl
- test/apply_fixes/test_fail_on_missing_report_files.py
Ref: https://github.com/codespell-project/codespell
> Typo fixes using codespell

- test/aspect/custom_config/aspect.bzl
- test/aspect/execute_tests.py
the full_custom_config.json file no longer exists/used. Just remove it.
> Test: remove non-existent full_custom_config.json for custom_config

- src/analyze_includes/evaluate_includes.py
- src/analyze_includes/parse_source.py
Fix readability issues found when reading code for `analyze_includes`.
> Improve readability by being more "pythonic"

- README.md
Resolves https://github.com/martis42/depend_on_what_you_use/issues/83
> Fix link in documentation

- README.md
Update doc for changes in https://github.com/martis42/depend_on_what_you_use/pull/77
> Specify more precisely the pattern matching

- src/analyze_includes/test/parse_source_test.py
- test/aspect/custom_config/BUILD
- test/aspect/custom_config/ignore_include_patterns.json
- test/aspect/custom_config/use_ignored_patterns.h
- test/aspect/custom_config/use_not_ignored_header.h
- test/aspect/execute_tests.py
Follow up to https://github.com/martis42/depend_on_what_you_use/pull/77
> More detailed tests for include path ignore patterns

- src/analyze_includes/parse_source.py
- src/analyze_includes/test/data/commented_includes/single_line_comments.h
- src/analyze_includes/test/parse_source_test.py
Less if statements inside the loop and more readable string comparisons.
Follow up to https://github.com/martis42/depend_on_what_you_use/pull/87
> Simplify parsing of include statements

- README.md
Resolves: https://github.com/martis42/depend_on_what_you_use/issues/70
DWYU has some benefits over layering_check. While layering_check might be the best option for some users, there are enough unique points for DWYU to justify a continuous development of DWYU for now.
> Update documentation for DWYU alternatives

- .bazelrc
- .gitignore
Make the pattern compliant to how the Bazel project does it:
- https://github.com/bazelbuild/bazel/blob/8482c7cf494686eb7498cec6ee58dad03b07ef0d/.bazelrc#L42
- https://github.com/bazelbuild/rules_rust/blob/ba0fb5956c0b9ef94928ceca566268ef3c9cdbb9/.bazelrc#L41
> Make custom bazelrc pattern compliant to the upstream pattern

- .bazelrc
- README.md
- docs/project_design_rationales.md
- test/aspect/execute_tests.py
- test/aspect/execute_tests_impl.py
- test/aspect/execute_tests_utest.py
Resolve https://github.com/martis42/depend_on_what_you_use/issues/119
> Update minimum bazel version to 5 0

- .github/dependabot.yaml
based on https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
> Ensure GitHub Actions remain up to date

- .github/workflows/ci.yaml
- all_tests.sh
- src/apply_fixes/buildozer_executor.py
- test/README.md
- test/apply_fixes/README.md
- test/aspect/REAME.md
Also consistently name high level tests 'integration test'
Resolves https://github.com/martis42/depend_on_what_you_use/issues/8
> Execute apply fixes integration tests on CI

- CONTRIBUTING.md
- README.md
- docs/concept_behind_dwyu.md
- docs/project_design_rationales.md
- test/apply_fixes/README.md
- test/aspect/REAME.md
- test/aspect/tree_artifact/README.md
- Introduce and document a new style regarding wrapping:
- Each sentence starts in a new line
- No wrapping
- Consistent style to enforce a newline
- Consistent style in examples using A, B, X and similar as placeholders for arbitrary entities
- Remove some outdated information
- Fix typos
- Streamline several sentences
> Refactor documentation

- README.md
- src/analyze_includes/parse_source.py
- src/analyze_includes/test/BUILD
- src/analyze_includes/test/data/include_based_on_pre_processor_token.h
- src/analyze_includes/test/parse_source_test.py
- test/aspect/defines/BUILD
- test/aspect/defines/include_using_pre_processor_token.h
Resolves https://github.com/martis42/depend_on_what_you_use/issues/147
> Enable parsing of pre processor tokens as include path

- BUILD
- README.md
- defs.bzl
- docs/project_design_rationales.md
- src/aspect/factory.bzl
- test/aspect/target_mapping/mapping/BUILD
- [Update documentation](https://github.com/martis42/depend_on_what_you_use/commit/03f05cb53fdb900bd0b3e8ea8b9b577f44895966)
- [Ensure mypyi config stays private to DWYU](https://github.com/martis42/depend_on_what_you_use/commit/6b20e3dec7de926788818fed1fbc1197b46574ac)
- [Ensure user can easily load all relevant symbols](https://github.com/martis42/depend_on_what_you_use/commit/47c994aa8ee1e9d1270115f2606831ddab2a156b)
> Some Cleanup

- .github/renovate.json
Individual PRs and thus individual commits are better for understanding what is going on
> Stop bundling renovate quality updates

- src/aspect/BUILD
> Remove superfluous export

- third_party/pcpp/recursion_fix.patch
- third_party/pcpp/repository.bzl
Fixes: https://github.com/martis42/depend_on_what_you_use/issues/300
> fix(aspect): Patch RecursionError in pcpp

- .bcr/presubmit.yml
- examples/test.py
Fixes https://github.com/martis42/depend_on_what_you_use/issues/322
> test(bcr): Be compatible to environment without bazelisk

- README.md
Fixes: https://github.com/martis42/depend_on_what_you_use/issues/348
> doc: Fix link to implementation_deps details

- CONTRIBUTING.md
- README.md
Fixes https://github.com/martis42/depend_on_what_you_use/issues/356
> doc: Update contribution guidelines

- src/analyze_includes/evaluate_includes.py
- src/analyze_includes/system_under_inspection.py
- src/analyze_includes/test/evaluate_includes_test.py
> perf(aspect): Fix extreme bad complexity

- scripts/count_release_downloads.py
- scripts/deploy_to_bcr.py
Also small update to release analysis script for consistent look and feel.
> chore: Automatically update BCR fork during deployment

- src/aspect/dwyu.bzl
- src/cc_toolchain_headers/private/gather_cc_toolchain_headers.bzl
Doing so is an anti pattern and can has a bad complexity.
> perf: Do not unroll depsets into lists

- .bazelignore
- .gitignore
- test/aspect/.bazelrc
- test/benchmark/aspect.bzl
- test/benchmark/bench_many_targets.py
- test/benchmark/bench_target_with_complex_code.py
- test/benchmark/bench_target_with_many_files.py
- test/benchmark/lib.py
Those new benchmarks analyze the whole analysis step for certain scenarios.
> test: Add benchmarks for overall DWYU performance

- docs/project_design_rationales.md
Maybe we come up with a heuristic to use the efficient preprocessor with its complete knowledge about defines eventually. But we can't use it "as is".
> doc: Explain why the CC toolchain preprocessor cannot be used
