- src/main.py
- test/custom_config/BUILD
- test/custom_config/aspect.bzl
- test/custom_config/extra_ignore_include_paths.json
- test/custom_config/full_custom_config.json
- test/custom_config/ignore_include_paths.json
- test/custom_config/use_arcane_header.h
- test/custom_config/use_arcane_header_and_vector.h
- test/custom_config/use_multiple_arcane_headers.h
- test/execute_tests.py
Allow specifying extra ignored include dirs without overwriting the
default ignore directories.
Resolves: https://github.com/martis42/depend_on_what_you_use/issues/21
> Make usage of configs more flexible for extra ignores

- .github/workflows/ci.yaml
pre-commit checks are executed as a dedicated job parallel to the `test` job.
Just in case that the user forgets about local execution, it's good that the CI checks in parallel.
From
* https://github.com/snok/install-poetry#workflow-examples-and-tips
* https://github.com/pre-commit/action#using-this-action
> Added pre-commit checks to CI

- .github/workflows/ci.yaml
* Bump used CI actions to latest
* Benefit from simplified configurations e.g. caching of dependencies
> Bump used CI actions

- src/analyze_includes/evaluate_includes.py
- src/analyze_includes/test/evaluate_includes_test.py
The `to_str` and `to_json` methods of `Report` returned different result for `invalid_includes`, and it turns out to be a bug in the `to_json` method of `Report`. This PR attempts to fix this.
> [AnalyzeIncludes]: bugfix for to_json method of Report

- README.md
- src/analyze_includes/evaluate_includes.py
- src/analyze_includes/test/evaluate_includes_test.py
- src/apply_fixes/main.py
- test/apply_fixes/src/test_case.py
- test/apply_fixes/test_cli_dry_run_performs_no_change.py
- test/apply_fixes/test_cli_use_custom_output_base.py
- test/apply_fixes/test_cli_utilize_bazel_info.py
- test/apply_fixes/test_fail_on_missing_report_files.py
- test/apply_fixes/test_remove_unused_private_dependency.py
- test/apply_fixes/test_remove_unused_public_dependency.py
- test/apply_fixes/workspace_template/BUILD
- test/apply_fixes/workspace_template/aspect.bzl
- test/apply_fixes/workspace_template/using_lib_a.cpp
- test/aspect/execute_tests.py
- test/aspect/execute_tests_impl.py
- test/aspect/execute_tests_utest.py
- test/aspect/unused_dep/BUILD
- test/aspect/unused_dep/aspect.bzl
- test/aspect/unused_dep/implementation_deps/BUILD
This changes the output format for the report files.
The entry `unused_deps` has been replaced by the 2 more specific entries `unused_public_deps` and `unused_private_deps`.
Automatically removing unused dependencies requires knowledge from which dependency attribute they should be removed. Thus, we adapt our output format to enable the automatic fixing script to work for code utilizing `implementation_deps`
> Automatix fixing supports private deps

- src/analyze_includes/evaluate_includes.py
- src/analyze_includes/test/evaluate_includes_test.py
- src/apply_fixes/main.py
We want to offer an automatic fix for invalid includes, where we search for a dependency which provides the header used in the target sources.
To be able to add the dependency correctly to either `deps` or `implementation_deps` we have to
> Distinguish between invalid public and private includes

- test/aspect/complex_includes/BUILD
- test/aspect/execute_tests.py
This PR attempts to fix the otherwise failing `//test/aspect/complex_includes:use_complex_includes_from_extern` case
when running from command line.
> Test: Fix the complex_includes testcase

- test/aspect/execute_tests.py
Without providing an aspect only a normal bazel is executed and no DWYU aspect is executed.
> Fix aspect test case

- src/aspect/dwyu.bzl
Starting from Bazel 6.0.0, `str(label)` returns `@//path/to:target` for target `//path/to:target` of the current workspace rather than `//path/to:target`. And having `@` in filenames or folders is generally discouraged. (E.g., https://www.mtu.edu/umc/services/websites/writing/characters-avoid/)
> Unified target label naming for DWYU-generated files

- src/analyze_includes/parse_source.py
- src/analyze_includes/test/parse_source_test.py
- test/aspect/custom_config/ignore_include_patterns.json
If instead we use `re.search(pattern, include)`, include `baz/a/b.h` will be matched against pattern `a/.*`, which should be an unexpected behavior.
> Use `re.match(pattern, include)` for ignored include patterns

- src/analyze_includes/parse_source.py
- src/analyze_includes/test/data/commented_includes/block_comments.h
- src/analyze_includes/test/parse_source_test.py
> Refactor get_includes_from_file to handle more include line cases

- src/aspect/dwyu.bzl
- test/aspect/execute_tests.py
- test/aspect/shared_library/BUILD
- test/aspect/shared_library/foo.cc
- test/aspect/shared_library/foo.h
Hi @martis42 
I found some cases w/ neither public-files nor private-files. Please help review whether or not it's OK.
> Handle the case where neither public-files nor private-files are present

- src/aspect/dwyu.bzl
- test/aspect/relative_includes/BUILD
- test/aspect/relative_includes/other/other.h
- test/aspect/relative_includes/use_normal_include.cpp
- test/aspect/relative_includes/use_system_include.cpp
- test/aspect/relative_includes/use_virtual_prefix.cpp
- test/aspect/relative_includes/use_virtual_strip.cpp
- test/aspect/relative_includes/virtual_prefix.cpp
- test/aspect/relative_includes/virtual_strip.cpp
For the target under inspection we have to incorporate headers from 'srcs' for the relative includes logic. In contrast to dependencies, where we ignore headers from 'srcs'.
Fix https://github.com/martis42/depend_on_what_you_use/issues/100
> Fix regression for relative includes to own private headers

- test/apply_fixes/execution_logic.py
Python 3.10 deprecates `distutils`.
See https://peps.python.org/pep-0632/
> Make project compatible to Python 3.10

- src/analyze_includes/BUILD
- src/analyze_includes/parse_source.py
- src/analyze_includes/test/BUILD
- src/analyze_includes/test/parse_source_test.py
In this first step we simplify our own code by using a well tested preprocessor to prune commented code instead of relying on our own implementation.
In the future we will build on this and support resolving defines
> Use pcpp to parse C/C++ source code

- .pre-commit-config.yaml
- Defining a variable causes a warning from pre-commit
- The warning categories don't have to be synced due to only automatically fixable warnings being relevant for the first check and only manually fixable checks are relevant for the second check.
> More precise buildifier config

- .pre-commit-config.yaml
- README.md
- WORKSPACE
- setup_step_2.bzl
- src/analyze_includes/evaluate_includes.py
- src/analyze_includes/main.py
- src/analyze_includes/parse_source.py
- src/analyze_includes/system_under_inspection.py
- src/analyze_includes/test/BUILD
- src/analyze_includes/test/data/header_with_defines.h
- src/analyze_includes/test/data/headers_info_empty.json
- src/analyze_includes/test/data/headers_info_full.json
- src/analyze_includes/test/evaluate_includes_test.py
- src/analyze_includes/test/parse_source_test.py
- src/analyze_includes/test/system_under_inspection_test.py
- src/aspect/dwyu.bzl
- src/aspect/factory.bzl
- src/aspect/test/BUILD
- src/aspect/test/dwyu_test.bzl
- test/aspect/defines/BUILD
- test/aspect/defines/README.md
- test/aspect/defines/defines_from_bazel_target.h
- test/aspect/defines/in_file_defines.h
- test/aspect/defines/lib/BUILD
- test/aspect/defines/support/BUILD
- test/aspect/defines/transitive_defines_from_bazel_target.h
- test/aspect/execute_tests.py
- test/aspect/recursion/README.md
The preprocessor based on `pcpp`, which we introduced earlier, already allows processing defines in files and thus automatically skipping irrelevant include statements.
Now we utilize this preprocessor to enable processing defines which have been set through Bazel or internally in a file which is analyzed.
> Add basic support for processing preprocessor defines

- .pre-commit-config.yaml
- README.md
- docs/project_design_rationales.md
- src/__init__.py
- src/analyze_includes/__init__.py
- src/analyze_includes/evaluate_includes.py
- src/analyze_includes/parse_source.py
- src/analyze_includes/system_under_inspection.py
- src/analyze_includes/test/__init__.py
- src/analyze_includes/test/evaluate_includes_test.py
- src/analyze_includes/test/parse_config_test.py
- src/apply_fixes/apply_fixes.py
- src/apply_fixes/buildozer_executor.py
- src/apply_fixes/summary.py
- src/apply_fixes/test/summary_test.py
- test/apply_fixes/execute_tests.py
- test/apply_fixes/execution_logic.py
- test/apply_fixes/test_case.py
- test/aspect/execute_tests_impl.py
This increases the minimum Python version required to use this project to 3.8.
Changes motivated by new Python version:
- Use modern `subprocess.run` API
- Use `dataclass`
Generic Python refactoring:
- More specific typing, no longer use `Any`
- Remove superfluous `__init__.py` files
- Fix typos
- Inline some expressions
Resolves: https://github.com/martis42/depend_on_what_you_use/issues/117
> Update project to use Python 3.7 and 3.8 features

- src/aspect/dwyu.bzl
- test/aspect/execute_tests.py
- test/aspect/execute_tests_impl.py
- test/aspect/execute_tests_utest.py
- test/aspect/unused_dep/BUILD
> Use `no-dwyu` tag to allow skipping checks on specific targets.

- .github/workflows/ci.yaml
- test/aspect/execute_tests_impl.py
- test/aspect/execute_tests_utest.py
Resetting bazel-out to use another Bazel version takes almost as long as executing the integration tests. Thus, we use a dedicated output directory for each Bazel version. This significantly speeds up consecutively executing the integration tests multiple times.
> Optimize aspect integration tests

- README.md
- dev_setup_step_2.bzl
- setup_step_2.bzl
- test/aspect/execute_tests.py
- test/aspect/execute_tests_impl.py
We add hermetic Python toolchains for development. This allows reproducible behavior across multiple developer machines.
Furthermore, this allows us to easily test multiple Python versions. This is important since a significant part of DWYU is implemented in Python.
Related to https://github.com/martis42/depend_on_what_you_use/issues/8
Fixes https://github.com/martis42/depend_on_what_you_use/issues/42
> Use multiple Python versions for aspect integration tests

- src/analyze_includes/evaluate_includes.py
- src/analyze_includes/system_under_inspection.py
- src/analyze_includes/test/data/dep_info_bar.json
- src/analyze_includes/test/data/dep_info_foo.json
- src/analyze_includes/test/data/implementation_dep_info_bar.json
- src/analyze_includes/test/data/implementation_dep_info_foo.json
- src/analyze_includes/test/data/target_under_inspection.json
- src/analyze_includes/test/data/target_under_inspection_empty.json
- src/analyze_includes/test/evaluate_includes_test.py
- src/analyze_includes/test/system_under_inspection_test.py
- src/aspect/dwyu.bzl
- src/aspect/process_target.py
The old approach was based on the first experiments regarding DWYU. We did infer the paths at which headers can be included instead of relying on the information from the CcInfoo compilation_context. This has several drawbacks:
- The code is needlessly complex. There is no reason why we should require a custom logic. In contrast, we have to take care about special cases like external workspaces, which Bazel already handles.
- We introduce various assumptions which we did not motivate properly nor test properly
- Not having the include paths available in the analysis as they are available to the compiler is a limiting factor for using the preprocessor to parse defines
> Rework include path analysis

- README.md
- src/analyze_includes/evaluate_includes.py
- src/analyze_includes/test/evaluate_includes_test.py
- test/aspect/relative_includes/use_system_include.cpp
- test/aspect/relative_includes/use_virtual_prefix.cpp
- test/aspect/relative_includes/use_virtual_strip.cpp
Recent improvements allows us to finally resolve this limitation of DWYU. This is is a niche use case, and doing relative includes to virtual paths is something I would consider a bad practice. Still, given it compiles DWYU should be able to analyze it.
> Support relative include statements for virtual paths

- src/aspect/dwyu.bzl
- src/aspect/factory.bzl
We have to skip targets not providing CcInfo not just because of incompatible targets in old Bazel versions, but also due to bug: https://github.com/bazelbuild/bazel/issues/19609
Given incompatible targets for aspects have been fixed in recent Bazel versions and the bug above has just been discovered, it makes no sense to keep mentioning incompatible targets as when above bug is fixed and we can remove this manual check for CcInfo incompatible targets are no longer relevant either way.
Resolves: https://github.com/martis42/depend_on_what_you_use/issues/33
> Change rationale for manually looking for CcInfo

- src/aspect/dwyu.bzl
In deeply nested workspace and/or long target names the paths for the various DWYU artifacts can become quite long. At some point they are too large for Bazel and the OS to handle and consequently DWYU fails.
We fix this by:
- We use only the name of the to be analyzed target instead of its full label as prefix for the DWYU artifacts. The artifacts are generated inside bazel-out in the package location of the to be analyzed target and thus the name is sufficient as suffix to guarantee unique results.
- For the DWYU artifacts depending on dependencies we no longer use the dependency label as path suffix, but instead use the hash of the label. This gives us an upper bound on the max length of the generated file names while still making name collision quite unlikely. That the names are less …
> Fix issue with long path names.

- src/analyze_includes/evaluate_includes.py
- src/analyze_includes/main.py
- src/analyze_includes/result.py
- src/analyze_includes/system_under_inspection.py
- src/analyze_includes/test/evaluate_includes_test.py
- src/analyze_includes/test/result_test.py
- src/analyze_includes/test/system_under_inspection_test.py
- src/apply_fixes/apply_fixes.py
- src/aspect/dwyu.bzl
We keep the long name in documentation and public APIs. But internally we use a shorter name which eases reading the code and is consistent to us already using `deps` instead of `dependencies`.
> Consistently use impl_deps for implementation_deps internally

- .bazelrc
- dev_setup_step_2.bzl
- dev_setup_step_3.bzl
- third_party/BUILD
- third_party/dev_dependencies.bzl
The latest version decouples the mypy Bazel integration from the mypy library. This eases integrating it into other projects like DWYU.
> Update Bazel mypy integration

- README.md
- WORKSPACE
- setup_step_2.bzl
- setup_step_3.bzl
- setup_step_4.bzl
- test/apply_fixes/execution_logic.py
- third_party/dependencies.bzl
rules_python develops at a steady pace and we want to keep our toolchain up to date. Also, we want to start supporting bzlmod soon, which profits from using a recent rules_python version.
> Update rules_python to 0.27.0

- README.md
- src/aspect/dwyu.bzl
- test/apply_fixes/test_case.py
- test/aspect/execute_tests_impl.py
- test/aspect/execute_tests_utest.py
- test/aspect/recursion/rule.bzl
There is no strong reason for this change. I am however not happy with the name chosen by me in the early project phase. Since, version 0.1.0 will soonish happen (aka jumping from alpha status to beta level) I want to do this breaking change now, before the project enters a phase in which such changes no longer should happen without strong reasons. Some concrete issues with the old name:
- The `cc_` prefix does not provide any meaningful information
- The `_output` postfix is redundant for something used with `--output_groups`
> Rename the DWYU output group

- .github/dependabot.yaml
- .github/renovate.json
Renovate supports Bazel (although we don't use it for now) and pre-commit updates which dependabot does not. GitHub Actions can be managed by both.
> Replace dependabot with renovate

- pyproject.toml
This does not change the minimum Python version DWYU supports in production. This only raises the minimum version required to be able to develop DWYU due to pre-commit deprecating Python 3.8 support early.
> Update minimum Python version for development to 3.9

- pyproject.toml
Saying >= 3.5 or newer sounds great at first, but actually it makes it hard to know what pre-commit version we actually use. The lock file pins to the latest version greater 3.5 at whatever time the lock was created. Thus, we pin pre-commit, but to know what we pin it to, one has to look into the longish lock file whereas one would expect the information in the pyprojects.toml file.
> Explicitly use pre-commit 3.6

- .bazelrc
- .github/workflows/ci.yaml
- examples/.bazelrc
- examples/MODULE.bazel
- examples/WORKSPACE
- examples/aspect.bzl
- examples/test.py
- test/aspect/ignore_includes/aspect.bzl
- test/aspect/target_mapping/aspect.bzl
- tests.sh
We need to provide targets from the root workspace to DWYU explicitly with labels as auto generating labels from strings does not work with bzlmod. With bzlmod the strings are converted in the wrong context to a label and thus cause visibility errors.
> Test examples with both workspace modi

- README.md
We use the git rules instead of the archive rules for fetching specific commits as the git rules are more elegant. This is either way intended for experimentation and not permanently referencing DWYU.
> Extend documentation for bzlmod

- .github/workflows/ci.yaml
- src/aspect/dwyu.bzl
- src/aspect/test/dwyu_test.bzl
- test/aspect/alias/test_invalid_dependency_through_alias.py
- test/aspect/defines/BUILD
- test/aspect/defines/defines_from_bazel_target.h
- test/aspect/defines/transitive_defines_from_bazel_target.h
- test/aspect/execution_logic.py
- test/aspect/ignore_includes/test_include_not_covered_by_patterns.py
- test/aspect/target_mapping/test_use_c_with_direct_deps_mapping.py
- test/aspect/target_mapping/test_use_c_with_specific_mapping.py
- test/aspect/tree_artifact/test_invalid_tree_artifact.py
- test/aspect/using_transitive_dep/test_detect_using_transitive_dep.py
- test/aspect/using_transitive_dep/test_detect_using_transitive_impl_dep.py
For now we execute the Windows based tests only for one Bazel and Python version as executing Python target on Windows is dramatically slow compared to Linux.
> Make aspect integrations tests wotk on Windows 

- README.md
- src/apply_fixes/apply_fixes.py
- src/apply_fixes/main.py
- test/apply_fixes/tool_cli/test_use_custom_output_base.py
For full details see individual commits
> Improve reports discovery speed

- .github/workflows/prepare_release.py
- .github/workflows/release.yaml
- scripts/count_release_downloads.py
Whenever a tag matching our versioning scheme is pushed, we automatically create and upload a draft release.
> Automate part of the release creation

- .github/renovate.json
- MODULE.bazel
- examples/MODULE.bazel
- examples/WORKSPACE
- test/apply_fixes/execution_logic.py
- test/aspect/MODULE.bazel
- test/aspect/WORKSPACE
- third_party/dependencies.bzl
We have no need for a newer version and 0.27.1 is the last version still supporting Bazel 5. Thus, we should use 0.27.1 as DWYU is as well still supporting Bazel 5.
While tests where green with 0.28.0, we don't want to risk problems in edge cases currently unknown to us.
> Downgrade rules python to 0.27.1

- .github/renovate.json
We should define the minimum version of each required dependency and not use the latest greatest version due to the bzlmod dependency resolution scheme which uses the minimum version of all requested ones. Thus, relying on the latest versions without need restricts usage of DWYU by users.
> No automated updates of main deps

- README.md
- scripts/count_release_downloads.py
- src/apply_fixes/apply_fixes.py
- src/apply_fixes/test/apply_fixes_test.py
- test/apply_fixes/missing_dependency/test_fail_on_ambiguous_dep_resolution.py
- test/apply_fixes/missing_dependency/test_fail_on_unavailable_include.py
- test/apply_fixes/missing_dependency/test_suggest_missing_dep_based_on_fallback_logic_using_header_file_name.py
- test/apply_fixes/missing_dependency/workspace/BUILD
- test/apply_fixes/missing_dependency/workspace/libs/BUILD
- test/apply_fixes/missing_dependency/workspace/libs/foo.h
- test/apply_fixes/missing_dependency/workspace/other_lib/BUILD
- test/apply_fixes/missing_dependency/workspace/other_lib/foo.h
- test/apply_fixes/missing_dependency/workspace/use_manipulated_bar.h
Our old logic fails when multiple dependencies provide a header file with the same name at different paths.
The new logic is robust against this due to looking for the full include path. Looking at the file name is now only a fallback used to resolve cases where include path manipulation makes a simple include path match impossible.
Fixes: https://github.com/martis42/depend_on_what_you_use/issues/237
>  apply_fixes: Improve dependency discovery heuristic

- src/apply_fixes/apply_fixes.py
- src/apply_fixes/main.py
- test/apply_fixes/tool_cli/test_forward_args_to_buildozer.py
This makes the buildozer-args option consistent to the bazel-args. Also it removes the restriction of `--buildozer-args` having to be the last argument.
Furthermore, we:
- Fix typos
- Reorder options. Subjectively this order is more natural from most important to least important and somewhat consistent in itself.
> Apply_fixes: Consistent CLI

- src/apply_fixes/apply_fixes.py
- src/apply_fixes/main.py
- test/apply_fixes/tool_cli/test_forward_args_to_buildozer.py
- test/apply_fixes/tool_cli/test_utilize_bazel_info_with_custom_compilation_mode.py
In some workspaces users have to provide custom arguments to use 'bazel info', which is now possible.
Resolves: https://github.com/martis42/depend_on_what_you_use/pull/246
> apply_fixes: More flexible bazel-info usage

- src/aspect/dwyu.bzl
- test/aspect/target_mapping/BUILD
- test/aspect/target_mapping/test_use_b_via_impl_deps_with_specific_mapping.py
A code path required for implementation_deps was missing, which is now fixed.
Resolves https://github.com/martis42/depend_on_what_you_use/issues/253
> Fix target_mapping not working with implementation_deps

- README.md
- src/analyze_includes/main.py
- src/analyze_includes/result.py
- src/analyze_includes/test/result_test.py
- src/apply_fixes/BUILD
- src/apply_fixes/apply_fixes.py
- src/apply_fixes/get_dwyu_reports.py
- src/apply_fixes/main.py
- src/apply_fixes/test/BUILD
- src/apply_fixes/test/get_dwyu_reports_test.py
- src/apply_fixes/test/utils_test.py
- src/apply_fixes/utils.py
- test/apply_fixes/test_case.py
- test/apply_fixes/tool_cli/test_get_dwyu_reports_from_execution_log.py
- test/apply_fixes/tool_cli/workspace/BUILD
- test/apply_fixes/tool_cli/workspace/sub/foo/BUILD
For large workspaces discovering the DWYU report files by crawling the bazel-out directory can be quite slow due to an enormous amount of files and directories being present.
To work around this, we enable the apply_fixes script to parse a log file containing the command line output of executing the DWYU aspect. This execution log is then parsed and the DWYU report paths deduced.
> apply_fixes can parse report files from a DWYU execution log

- src/aspect/dwyu.bzl
- All actions should have a mnemonic. This allows centrally setting certain attributes for all actions of a certain kind
- Use 'Dwyu' prefix to make sure they are unique
> Actions should offer a proper mnemonic

- test/apply_fixes/execution_logic.py
- test/apply_fixes/missing_dependency/test_find_external_dependency.py
- test/apply_fixes/missing_dependency/workspace/external_dep/MODULE.bazel
- test/apply_fixes/missing_dependency/workspace/load_external_dep.bzl
- test/aspect/MODULE.bazel
- test/aspect/WORKSPACE
- test/aspect/execute_tests.py
- test/aspect/execution_logic.py
- test/aspect/version.py
> Refactor integration testing

- .bcr/presubmit.yml
20.04 is quite old by now and our CI uses also 22.04
> Update Ubuntu in BCR tests

- src/apply_fixes/search_missing_deps.py
It seems that not all targets that explicitly specify the `hdrs` attribute also have the `stringListValue` present.
> Work around missing "stringListValue" in certain cases

- poetry.lock
This allows dropping the setuptools dependency, which also resolves the vulnerability warning associated with using setuptools < 70.0.
> chore: Update pre-commit to 3.8.0

- src/aspect/dwyu.bzl
- src/aspect/process_target.py
Without a param file invocations fail with "Argument list too long" when run on larger projects.
> Use param files to invoke process_target.py

- src/analyze_includes/evaluate_includes.py
- src/analyze_includes/test/evaluate_includes_test.py
- test/aspect/multiple_deps_for_one_header/BUILD
- test/aspect/multiple_deps_for_one_header/foo.h
- test/aspect/multiple_deps_for_one_header/test_multiple_deps_for_one_header.py
Such cases shall not cause the DWYU dependency to report an unused dependency.
Fixes https://github.com/martis42/depend_on_what_you_use/issues/289
> fix(aspect): Allow multiple dependencies providing the same header

- src/aspect/dwyu.bzl
- src/aspect/process_target.py
- test/aspect/command_length_limit/BUILD
- test/aspect/command_length_limit/make_large_arg.bzl
- test/aspect/command_length_limit/test_command_length_limit.py
Bazel can detect whether a param file is required. We ensure this works as desired by adding a test.
> refactor(aspect): Only use a param file if required

- .github/workflows/ci.yaml
`macos-12` has been deprecated by GitHub.
> chore: Update CI test environment

- .bcr/presubmit.yml
- MODULE.bazel
- README.md
- setup_step_2.bzl
- test/aspect/execute_tests.py
With the release of Bazel 8, Bazel 5 is deprecated. This step unblocks updates of our dependencies to recent versions.
BREAKING CHANGE: Bazel 6.0.0 is now the minimum version for DWYU.
> build: Drop Bazel 5.x support

- MODULE.bazel
- scripts/BUILD
- scripts/test/BUILD
- src/analyze_includes/BUILD
- src/analyze_includes/test/BUILD
- src/apply_fixes/BUILD
- src/apply_fixes/test/BUILD
- src/aspect/BUILD
- src/aspect/dwyu.bzl
- src/cc_info_mapping/private/BUILD
- src/cc_info_mapping/private/direct_deps.bzl
- src/cc_info_mapping/private/explicit.bzl
- src/cc_info_mapping/private/transitive_deps.bzl
- test/aspect/tree_artifact/BUILD
- third_party/dependencies.bzl
- third_party/pcpp/pcpp.BUILD
User facing changes:
Updating minimum required version for `rules_cc` to 0.15.0
> Use modern language rules load statements

- src/analyze_includes/BUILD
- src/apply_fixes/BUILD
- test/apply_fixes/execution_logic.py
- test/aspect/execute_tests.py
- third_party/pcpp/pcpp.BUILD
Some users require this setting to mitigate issues due to a large `PYTHONPATH` created by rules_python.
Fixes: https://github.com/martis42/depend_on_what_you_use/issues/293
> feat: Support --noexperimental_python_import_all_repositories

- .github/renovate.json
> Streamline renovate behavior and config

- src/analyze_includes/system_under_inspection.py
- src/analyze_includes/test/data/target_under_inspection.json
- src/analyze_includes/test/data/target_under_inspection_empty.json
- src/analyze_includes/test/system_under_inspection_test.py
- src/aspect/dwyu.bzl
- src/aspect/process_target.py
- src/utils/utils.bzl
- test/aspect/complex_includes/test_feature_external_include_paths.py
When this feature is active, some include paths in `CompilationContext` are automatically moved to `external_includes`. This allows Bazel to pass them to the compiler via `-isystem` to silence compiler warnings for external headers.
DWYU is however only compatible to `external_include_paths` starting from Bazel 7.0.0.
Resolves: https://github.com/martis42/depend_on_what_you_use/issues/299
> feat(aspect): support toolchain feature external_include_paths

- .github/workflows/prepare_release.py
- .github/workflows/release.yaml
We can't use draft releases. With drafts, the attached artifacts have a temporary download path different from the one available in the final release. This makes it impossible to use a draft Release for creating the BCR PR.
> refactor(ci): Drop superfluous release step and ease BCR deployment

- test/apply_fixes/missing_dependency/workspace/BUILD
- test/apply_fixes/missing_dependency/workspace/libs/BUILD
Test case for the bug fixed in:
https://github.com/martis42/depend_on_what_you_use/pull/280
> test(apply_fixes): Test empty list attributes

- src/cc_info_mapping/private/direct_deps.bzl
- src/cc_info_mapping/private/transitive_deps.bzl
- test/aspect/target_mapping/libs/BUILD
Resolves an issue reported in context of https://github.com/martis42/depend_on_what_you_use/issues/341
Based on this contribution https://github.com/martis42/depend_on_what_you_use/pull/342. I extended the fix to direct deps management and added tests
> fix(aspect): Ignore non cc deps in target_mapping

- test/aspect/execute_tests.py
- test/aspect/execution_logic.py
Allows us to test the latest Bazel versions with less maintenance effort due to regularly bumping versions.
> test(aspect): Support and use more dynamic version specifiers

- .bcr/presubmit.yml
One cannot omit the patch version. We now simply use the latest version of Bazel 6.
We wanted to use explicitly 6.4.x as this is our minimum required version. There is however no compelling reason to use the BCR to test our minimal required Bazel version. Our own CI already takes care of testing this.
> test(bcr): Fix presubmit tests Bazel versions

- src/aspect/dwyu.bzl
- src/aspect/factory.bzl
- src/cc_info_mapping/cc_info_mapping.bzl
- src/cc_info_mapping/private/direct_deps.bzl
- src/cc_info_mapping/private/explicit.bzl
- src/cc_info_mapping/private/providers.bzl
- src/cc_info_mapping/private/transitive_deps.bzl
- src/cc_info_mapping/providers.bzl
BREAKING CHANGE: The old names were easily mixed up. `DwyuCcInfoRemappingsInfo` was publily visible. Thus, this is a breaking change. But users were never expected to use it, so this has most likely no real impact.
> refactoring: Rename providers for CcInfo remapping feature
